from typing import List, Tuple

games_db: List[Tuple[str, str, str, int, List[str]]] = [
    (
        "4-2",  # final score
        "Uruguay",  # winning team
        "Argentina",  # losing team
        1930,  # year
        [
            "Nasazzi",  # winning team captain
            "Ferreira",  # losing team captain
        ],  # captains, winning team first
    ),
    (
        "2-1",
        "Italy",
        "Czechoslovakia",
        1934,
        [
            "Combi",
            "Planicka",
        ],
    ),
    (
        "4-2",
        "Italy",
        "Hungary",
        1938,
        [
            "Ferrari",
            "Szalay",
        ],
    ),
    (
        "4-2",
        "Uruguay",
        "Brazil",
        1950,
        [
            "Nasazzi",
            "Augusto",
        ],
    ),
    (
        "3-2",
        "Germany",
        "Hungary",
        1954,
        [
            "Walter",
            "Bozsik",
        ],
    ),
    (
        "5-2",
        "Brazil",
        "Sweden",
        1958,
        [
            "Bellini",
            "Liedholm",
        ],
    ),
    (
        "3-2",
        "Brazil",
        "Czechoslovakia",
        1962,
        [
            "Ramos",
            "Dobias",
        ],
    ),
    (
        "4-2",
        "England",
        "Germany",
        1966,
        [
            "Moore",
            "Seeler",
        ],
    ),
    (
        "4-1",
        "Brazil",
        "Italy",
        1970,
        [
            "Alberto",
            "Facchetti",
        ],
    ),
    (
        "2-1",
        "Germany",
        "Netherlands",
        1974,
        [
            "Beckenbauer",
            "Suurbier",
        ],
    ),
    (
        "3-1",
        "Argentina",
        "Netherlands",
        1978,
        [
            "Passarella",
            "Krol",
        ],
    ),
    (
        "3-2",
        "Italy",
        "Germany",
        1982,
        [
            "Zoff",
            "Rummenigge",
        ],
    ),
    (
        "3-0",
        "Argentina",
        "Germany",
        1986,
        [
            "Maradona",
            "Rummenigge",
        ],
    ),
    (
        "0-0 (a.e.t., 3-2 pens)",
        "Germany",
        "Argentina",
        1990,
        [
            "Matthäus",
            "Maradona",
        ],
    ),
    (
        "3-0",
        "Brazil",
        "Italy",
        1994,
        [
            "Dunga",
            "Maldini",
        ],
    ),
    (
        "3-0",
        "France",
        "Brazil",
        1998,
        [
            "Deschamps",
            "Cafu",
        ],
    ),
    (
        "2-0",
        "Brazil",
        "Germany",
        2002,
        [
            "Cafu",
            "Kahn",
        ],
    ),
    (
        "1-1 (a.e.t., 5-3 pens)",
        "Italy",
        "France",
        2006,
        [
            "Cannavaro",
            "Thuram",
        ],
    ),
    (
        "1-0 (a.e.t.)",
        "Spain",
        "Netherlands",
        2010,
        [
            "Casillas",
            "van Bronckhorst",
        ],
    ),
    (
        "1-0",
        "Germany",
        "Argentina",
        2014,
        [
            "Lahm",
            "Messi",
        ],
    ),
    (
        "4-2",
        "France",
        "Croatia",
        2018,
        [
            "Lloris",
            "Modric",
        ],
    ),
    (
        "2-0",
        "Argentina",
        "France",
        2022,
        [
            "Messi",
            "Mbappe",
        ],
    )
]

# Example of accessing the data for the 1930 World Cup final
print("Final score:", games_db[0][0])
print("Winning team:", games_db[0][1])
print("Losing team:", games_db[0][2])
print("Year:", games_db[0][3])
print("Captains:", games_db[0][4])