from typing import List, Tuple

games_db: List[Tuple[str, str, str, int, List[str]]] = [
    (
        "4-2",  # final score
        "uruguay",  # winning team
        "argentina",  # losing team
        1930,  # year
        [
            "nasazzi",  # winning team captain
            "ferreira",  # losing team captain
        ],  # captains, winning team first
    ),
    (
        "2-1",
        "italy",
        "czechoslovakia",
        1934,
        [
            "combi",
            "flanicka",
        ],
    ),
    (
        "4-2",
        "italy",
        "hungary",
        1938,
        [
            "ferrari",
            "szalay",
        ],
    ),
    (
        "4-2",
        "uruguay",
        "brazil",
        1950,
        [
            "nasazzi",
            "augusto",
        ],
    ),
    (
        "3-2",
        "germany",
        "hungary",
        1954,
        [
            "walter",
            "bozsik",
        ],
    ),
    (
        "5-2",
        "brazil",
        "sweden",
        1958,
        [
            "bellini",
            "liedholm",
        ],
    ),
    (
        "3-2",
        "brazil",
        "czechoslovakia",
        1962,
        [
            "ramos",
            "dobias",
        ],
    ),
    (
        "4-2",
        "england",
        "germany",
        1966,
        [
            "moore",
            "seeler",
        ],
    ),
    (
        "4-1",
        "brazil",
        "italy",
        1970,
        [
            "alberto",
            "facchetti",
        ],
    ),
    (
        "2-1",
        "germany",
        "netherlands",
        1974,
        [
            "beckenbauer",
            "suurbier",
        ],
    ),
    (
        "3-1",
        "argentina",
        "netherlands",
        1978,
        [
            "passarella",
            "krol",
        ],
    ),
    (
        "3-2",
        "italy",
        "germany",
        1982,
        [
            "zoff",
            "rummenigge",
        ],
    ),
    (
        "3-0",
        "argentina",
        "germany",
        1986,
        [
            "maradona",
            "rummenigge",
        ],
    ),
    (
        "0-0 (a.e.t., 3-2 pens)",
        "germany",
        "argentina",
        1990,
        [
            "matthäus",
            "maradona",
        ],
    ),
    (
        "3-0",
        "brazil",
        "italy",
        1994,
        [
            "dunga",
            "maldini",
        ],
    ),
    (
        "3-0",
        "france",
        "brazil",
        1998,
        [
            "deschamps",
            "cafu",
        ],
    ),
    (
        "2-0",
        "brazil",
        "germany",
        2002,
        [
            "cafu",
            "kahn",
        ],
    ),
    (
        "1-1 (a.e.t., 5-3 pens)",
        "italy",
        "france",
        2006,
        [
            "cannavaro",
            "thuram",
        ],
    ),
    (
        "1-0 (a.e.t.)",
        "spain",
        "netherlands",
        2010,
        [
            "casillas",
            "van bronckhorst",
        ],
    ),
    (
        "1-0",
        "germany",
        "argentina",
        2014,
        [
            "lahm",
            "messi",
        ],
    ),
    (
        "4-2",
        "France",
        "Croatia",
        2018,
        [
            "lloris",
            "modric",
        ],
    ),
    (
        "2-0",
        "argentina",
        "france",
        2022,
        [
            "messi",
            "lloris",
        ],
    )
]

# Example of accessing the data for the 1930 World Cup final
# print("Final score:", games_db[0][0])
# print("Winning team:", games_db[0][1])
# print("Losing team:", games_db[0][2])
# print("Year:", games_db[0][3])
# print("Captains:", games_db[0][4])